# Automated management of Dependabot PRs
name: Dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - uses: ministryofjustice/hmpps-probation-integration-services/.github/actions/dependabot-automerge@main
        with:
          token: ${{ steps.app-token.outputs.token }}
