name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI"
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v2
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      subproject: ndelius-new-tech-pdf-generator
    secrets: inherit
