name: Security Veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * MON-FRI"
jobs:
  security-veracode-pipeline-scan:
    name: Security Veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@96b1ed2a59da5e9b1c97b03f02d7e0e067ab82aa
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
      HMPPS_VERACODE_API_ID_0: ${{ secrets.HMPPS_VERACODE_API_ID_0 }}
      HMPPS_VERACODE_API_ID_1: ${{ secrets.HMPPS_VERACODE_API_ID_1 }}
      HMPPS_VERACODE_API_ID_2: ${{ secrets.HMPPS_VERACODE_API_ID_2 }}
      HMPPS_VERACODE_API_ID_3: ${{ secrets.HMPPS_VERACODE_API_ID_3 }}
      HMPPS_VERACODE_API_ID_4: ${{ secrets.HMPPS_VERACODE_API_ID_4 }}
      HMPPS_VERACODE_API_KEY_0: ${{ secrets.HMPPS_VERACODE_API_KEY_0 }}
      HMPPS_VERACODE_API_KEY_1: ${{ secrets.HMPPS_VERACODE_API_KEY_1 }}
      HMPPS_VERACODE_API_KEY_2: ${{ secrets.HMPPS_VERACODE_API_KEY_2 }}
      HMPPS_VERACODE_API_KEY_3: ${{ secrets.HMPPS_VERACODE_API_KEY_3 }}
      HMPPS_VERACODE_API_KEY_4: ${{ secrets.HMPPS_VERACODE_API_KEY_4 }}
